name: Build and Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-*)'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.3"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pdoc3
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*

  publish:
    runs-on: ubuntu-latest
    needs: build  # This ensures the publish job runs after the build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install Twine
        run: python -m pip install --upgrade twine

      - name: Publish package to repo
        run: |
          twine upload --repository-url todo